### ISSUE TITLE
Add rule for factcheck.org

### ISSUE THREAD

**Issue by BK1233** [EFForg/https-everywhere#10819]
factcheck.org is HTTPS enabled but not by default.

**Comment by Bisaloo** [comment]
I created a ruleset in #10825 but it will be off by default because https://www.factcheck.org/ has active mixed content issues.

**Comment by numismatika** [comment]
@Bisaloo  i only see passive mixed content problems from dev.factcheck.org so far from a couple of pictures.

**Comment by bardiharborow** [comment]
@Bisaloo the issue appears to have been resolved apart from `http://dev.factcheck.org/UploadedFiles/2017/03/SOTU_0329.png` and `http://cdn.factcheck.org/UploadedFiles/Greenfield_donatenow.png`.

**Comment by Bisaloo** [comment]
Nope. Not sure why but I am still having the issues I mentioned earlier.
