### ISSUE TITLE
geocaching.com various issues

### ISSUE THREAD

**Issue by ertyu** [EFForg/https-everywhere#1567]
I've run across several issues with SSL usage and the behaviour https-everywhere is forcing for this site.

blog.geocaching.com -- www.geocaching.com/blog
fails to render pages correctly when connected under https, many pages even start generating 404 errors

www.geocaching.com
doesn't appear to get rewritten to https as the site forces it back, but ajax calls start silently breaking with https-everywhere enabled, things like percentages of favourites or loading more logs that are dynamically pulled in fail

**Comment by jovandeginste** [comment]
Would this now be fixed in the firefox public addon? I still have failures when updating cache notes - url like: POST http://www.geocaching.com/seek/cache_details.aspx/SetUserCacheNote

**Comment by ertyu** [comment]
It didn't fix things when I last tried, I just manually disable the site.
