### ISSUE TITLE
Add aliases to Posteo ruleset

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#16187]
Type: other

- [ ] Posteo.af
- [ ] Posteo.at
- [ ] Posteo.be
- [ ] Posteo.ch
- [ ] Posteo.cl
- [ ] Posteo.co
- [ ] Posteo.co.uk
- [ ] Posteo.com.br
- [ ] Posteo.cr
- [ ] Posteo.cz
- [ ] Posteo.dk
- [ ] Posteo.ee
- [ ] Posteo.es
- [ ] Posteo.eu
- [ ] Posteo.fi
- [ ] Posteo.gl
- [ ] Posteo.gr
- [ ] Posteo.hn
- [ ] Posteo.hr
- [ ] Posteo.hu
- [ ] Posteo.ie
- [ ] Posteo.in
- [ ] Posteo.is
- [ ] Posteo.jp
- [ ] Posteo.la
- [ ] Posteo.li
- [ ] Posteo.lt
- [ ] Posteo.lu
- [ ] Posteo.me
- [ ] Posteo.mx 
- [ ] Posteo.my
- [ ] Posteo.net
- [ ] Posteo.nl
- [ ] Posteo.no
- [ ] Posteo.nz
- [ ] Posteo.org
- [ ] Posteo.pe
- [ ] Posteo.pl
- [ ] Posteo.pm
- [ ] Posteo.pt
- [ ] Posteo.ro
- [ ] Posteo.ru
- [ ] Posteo.se
- [ ] Posteo.sg
- [ ] Posteo.si
- [ ] Posteo.tn
- [ ] Posteo.uk
- [ ] Posteo.us

should lead to https://posteo.de

**Comment by youdly** [comment]
I suggest to merge other issues into one like https://github.com/EFForg/https-everywhere/issues/13603

**Comment by J0WI** [comment]
@tscpd I merged all Posteo issues into this one to reduce the noise.

**Comment by tscpd** [comment]
great. i was opening new isse because of the advice displayed by opening new ticket:

(domain to report, such as both "example.com" and "example.org", open a)
(new issue for each top-level domain.)

thanks for the work! cheers

**Comment by tscpd** [comment]
@Bisaloo  it looks like this rules did not take place till now, right? or am i wrong in my expectation? by typing Posteo.af for example i still get security-warning insted of leading me to https://posteo.de

**Comment by J0WI** [comment]
There was no PR provided so far. You're very welcome to [address this issue](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md). 😃

**Comment by tscpd** [comment]
amazing, i tryed to help, but please be patient with me; does this help or what to do next? https://github.com/tscpd/https-everywhere-rulesets/blob/master/posteo-de.xml

**Comment by J0WI** [comment]
You should start with a [fork](https://help.github.com/articles/fork-a-repo/) and apply your changes there.
Please double check your syntax before submitting a PR, the current file misses all closing brackets.

**Comment by tscpd** [comment]
i created a local Fork and the Branch posteo-de-2018083101. than i edited Posteo.xml. than i did "git add ./Posteo.xml" and "git commit ./Posteo.xml" - now im stuck - all i did is on my local machine, right?

**Comment by J0WI** [comment]
Then you have to `git push` it to your GitHub account and create a PR here.

**Comment by tscpd** [comment]
ive been trying to improve the rule; looks like i dont get it to work? https://github.com/EFForg/https-everywhere/pull/16443/commits/690844fe9cc7233b483cf2dd3f54af4bac74ff28
