### ISSUE TITLE
rule gmx.net wrong forward 

### ISSUE THREAD

**Issue by Itsalltext** [EFForg/https-everywhere#2630]
As fas as I see is the first test of the rule gmx.ch where I end up often. But I'm registered at gmx.net. So that I have to enter the https-adress at the first time manualy.

Please change it that after entering gmx.net I come to https://gmx.net.

Thanks

**Comment by rugk** [comment]
Done: https://github.com/EFForg/https-everywhere/pull/2632

Although the PR has some problems, but hopefully I get that fixed.

**Comment by donced** [comment]
Previously reported by https://github.com/EFForg/https-everywhere/issues/1895#issuecomment-124518687. PR which fixes the issue https://github.com/EFForg/https-everywhere/pull/2329

**Comment by merlin-s** [comment]
not fixed yet. https://github.com/EFForg/https-everywhere/issues/2337#issuecomment-172218249

**Comment by semenko** [comment]
Closing as duplicate, refer to #2337
