### ISSUE TITLE
install-dev-dependencies.sh and test.sh fail on Debian Jessie

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2801]
Currently, <code>install-dev-dependencies.sh</code> attempts to install <code>chromium-chromedriver</code> which is not part of the standard repositories. There is a package called <code>chromedriver</code> which perhaps(?) does the same thing.

The same script attempts to access <code>test/chrome/</code> which does not exist. The folder <code>test/chromium/</code> does, though.

Even with those two changes, <code>test.sh</code> still gives the following error:

```
ChromeDriver isn't installed. Check test/chrome/README.mdfor instructions on how to install ChromeDriver
```

**Comment by semenko** [comment]
Can you try rebasing to master? A bunch of this was fixed in #2779 -- though it won't fix the bug with `chromium-chromedriver` in Debian

(FYI @TheNavigat )

**Comment by TheNavigat** [comment]
Can you possibly assign this issue to me?

I don't think chromedriver is a standard package and therefore might not exist in Debians repositories. If there exists a package called chromedriver then that should be the same thing indeed, but we need to add a condition to install-dev-dependencies to either install the chromedriver package or download and install chromedriver manually.

I'm on a train right now and I don't havel enough connectivity or space, so it's a bit too difficult for me to check Debian's repos right now. Sorry :(

**Comment by semenko** [comment]
Sure -- chromium-chromedriver isn't in Debian -- it's just in Ubuntu it seems.

Perhaps do the same thing we've done in Travis (copy to testing path) and add `chromedriver` to .gitignore?

**Comment by TheNavigat** [comment]
That is possible indeed.

In this specific case though we can use sudo and move the thing to /usr/bin which I believe is much better an option.

**Comment by semenko** [comment]
Hm, I think some users are likely to be unhappy with us adding directly to their /usr/bin without a package manager.

**Comment by fuglede** [comment]
Sorry, was testing this on a master from a couple of hours ago; hadn't seen the latest changes. Anyway, I'm still getting the same error off the current master. Performing the 'chrome' -> 'chromium' change to <code>https-everywhere-tests/tests/test-httpse-installed</code> in #2803, the test stalls at

    Full Message: Error: Module: https-everywhere-tests/tests/test-httpse-installed has no authority to load: chromium
    Full Stack: @https-everywhere-tests/tests/test-httpse-installed:58:undefined
    resolve@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:58:1
    @resource://jid1-we5bqofc6sksmg-at-jetpack/https-everywhere-tests/tests/test-httpse-installed.js:3:20
    CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18
    findTests/</getNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:164:25
    findTests/</<.getNext@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:197:32
    runNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:516:14
    startMany@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:530:12
    findAndRunTests/<@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:28:1
    Handler.prototype.process@resource://gre/modules/Promise-backend.js:867:23
    this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:746:7
    this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:688:37
    " {file: "https-everywhere-tests/tests/test-httpse-installed" line: 58 column: 0 source: "58"}]

**Comment by semenko** [comment]
Gosh, that's a cool error! `has no authority to load: chromium`

@TheNavigat want to just blacklist Debian (or whitelist Ubuntu) for the Chromium tests until we get this sorted out?

**Comment by TheNavigat** [comment]
@semenko Mmmm... Alright then, copying it is.

And no, that error is different. It doesn't actually require Chrome or Chromium, it requires Chrome library, which is a completely different thing AFAIK (I have some experience developing Firefox addons). It's a library available for Firefox's SDK. Google something like "Firefox Chrome CC", if you'd like more details.

This seems weird for me because that shouldn't be related to whatever we've changed.

Can you try reverting to an old commit and running the file again? Something older than the whole restructuring thing.

We might blacklist Debian for now, but again, that makes no sense. It's possibly some small thing that broke it all, but it doesn't make sense that it's connected to our restructuring.

One thing that " might" be possible is if Chromium package doesn't install the libraries this file requires. Did you try installing Google Chrome before running that script?

**Comment by semenko** [comment]
Yeah, it's actually pretty strange. I'll try to spin up a Debian VM later tonight and take a look.

Maybe we're specifying some Google Chrome dependencies, when we're installing chromium? (Although you'd think that would fail on Travis, since it doesn't have Chrome, just chromium...)

**Comment by TheNavigat** [comment]
Ah, I think I understand it a bit more right now. That's simple, yet too confusing.

When you changed require Chrome to require Chromium you didn't push it forward, you crashed it before Chrome even had a chance to start. Therefore the Chromedriver doesn't exist message didn't even appear. You shouldn't change this file, it's perfectly correct.

The Chromedriver is missing message, on the other hand, is different and unrelated (although might seem so, confusingly). To fix that, we need to install chromedriver properly. Apparently we're not doing that when it comes to Debian.

Tl;Dr:

Revert the httpse-whatever file. It's original version is correct, and it's unrelated to the "Chromedriver is missing" message.
Write code to install Chromedriver correctly for Debian.
And then you'll be good to go.

**Comment by fuglede** [comment]
Probably I should have been more precise but the error about "ChromeDriver" not being installed was obtained after the [Debian package chromedriver](https://packages.debian.org/jessie/chromedriver) was installed.

**Comment by TheNavigat** [comment]
I'll be home in an hour, I'll take a look at this, would like nice if you guys were available on the IRC.

During that time can you try running Chromedriver manually through the terminal and confirming that it runs correctly? Can you check where was it installed? (I.e. chromedriver's path)

**Comment by fuglede** [comment]
The package produces an executable called <code>chromedriver</code>in <code>/usr/lib/chromium</code>.

**Comment by semenko** [comment]
Different than: https://github.com/EFForg/https-everywhere/blob/master/test/chromium/script.py#L37

We should clean up those path tests.

**Comment by TheNavigat** [comment]
https://github.com/EFForg/https-everywhere/pull/2811

That should fix it.

**Comment by fuglede** [comment]
Still unable to push:

    6 of 7 tests passed.

    The following tests failed:
      https-everywhere-tests/tests/test-httpse-installed.test httpse installed: failure

Tracing back, it looks like the relevant part is this one:

```bash
console.info: https-everywhere-tests: executing 'https-everywhere-tests/tests/test-httpse-installed.test httpse installed'
console.info: https-everywhere-tests: pass: Test that HTTPSEverywhere is defined
console.info: https-everywhere-tests: pass: Test that HTTPSEverywhere.observe is a function
console.error: https-everywhere-tests: 
  fail:
  There was an uncaught Promise rejection: Error: loop is not enabled @ resource:///modules/loop/MozLoopService.jsm:1110
this.MozLoopService.initialize<@resource:///modules/loop/MozLoopService.jsm:1110:29
TaskImpl_run@resource://gre/modules/Task.jsm:314:40
TaskImpl@resource://gre/modules/Task.jsm:275:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:249:14
LoopUI.init@chrome://browser/content/browser.js:4485:7
gBrowserInit._delayedStartup@chrome://browser/content/browser.js:11917:5

console.trace: https-everywhere-tests: 
_ecated/unit-test.js 108 fail
_ecated/unit-test.js 71 TestRunner.prototype._uncaughtErrorObserver
_/Promise-backend.js 200 PendingErrors.report
_/Promise-backend.js 212 PendingErrors.flush
_/Promise-backend.js 614 Promise.Debugging.flushUncaughtErrors
_ecated/unit-test.js 322 done
_ecated/unit-test.js 564 start
_ecated/unit-test.js 522 startMany/runNextTest/<
_/Promise-backend.js 867 Handler.prototype.process
_/Promise-backend.js 746 this.PromiseWalker.walkerLoop
_/Promise-backend.js 688 this.PromiseWalker.scheduleWalkerLoop/<
	             0
```

**Comment by TheNavigat** [comment]
That is too weird.

I'll try cloning the repo and running everything there, reverting to an old commit and trying again, etc... Maybe something's wrong with your instance :/

**Comment by fuglede** [comment]
Not sure what you mean by instance, but I've checked it on two similar-but-different Jessie setups with the same result.

I haven't looked into the details of what the test actually tests but it would appear that it makes false assumptions on the capabilities of iceweasel: if I create a symlink from <code>/usr/bin/iceweasel</code> to a more recent version of Firefox than the one in Jessie (which is currently at 38.0), I don't get any failed tests. (I also only see 6 tests run instead of 7 but alas.)

**Comment by fuglede** [comment]
Homing in on it: if I add <code>user_pref("loop.enabled", true);</code> to [https-everywhere-tests/test_profile_skeleton/prefs.js](https://github.com/EFForg/https-everywhere/blob/master/https-everywhere-tests/test_profile_skeleton/prefs.js), then the test passes.

This setting toggles whether or not Firefox Hello is enabled, so the natural question is why the test checks for that, as Hello functionality should be disjoint from HTTPS-E(?)

Another natural question is what happens for users who do not have Hello-capable browsers at all (Debian stable only fairly recently got a version where Hello was available).

**Comment by semenko** [comment]
Yeah, very strange. (And looks like unrelated to @TheNavigat's work.)

We'll probably want input from someone with experience in the FF tests -- I'm not entirely clear about their design.

**Comment by TheNavigat** [comment]
I use "instances" to test stuff, or cloud servers. That's what I meant with "instance" :)

I'll do a little bit more testing right now. Hopefully it'll move us a bit forward on this issue.

**Comment by semenko** [comment]
Here's a quick docker repro:

```
$ docker pull debian:jessie
$ docker run -ti --rm --net=host -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix debian:jessie /bin/bash
[in docker]
$ cd 
$ apt-get update
$ apt-get install -y git sudo lsb-release lib32z1-dev libssl-dev
$ git clone https://github.com/EFForg/https-everywhere.git
$ cd https-everywhere
$ ./install-dev-dependencies.sh

[snip]

/root/https-everywhere
+ cd test/chromium
+ pip install --user -r requirements.txt
Downloading/unpacking selenium (from -r requirements.txt (line 1))
  Downloading selenium-2.47.1-py2-none-any.whl (3.0MB): 3.0MB downloaded
Installing collected packages: selenium
Compiling /tmp/pip-build-ggFvb4/selenium/selenium/test/selenium/webdriver/browser_specific_template.py ...
  File "/tmp/pip-build-ggFvb4/selenium/selenium/test/selenium/webdriver/browser_specific_template.py", line 21
    from selenium.##PACKAGE_NAME## import ##GENERAL_FILENAME##
                                                             ^
SyntaxError: invalid syntax

Successfully installed selenium
Cleaning up...

[snip]

$ ./test.sh
```

I see the same Selenium error in Ubuntu. Maybe we can specify a version in pip?

**Comment by TheNavigat** [comment]
Okay, surprise surprise.

First, there's a missing package in install-dev-dependencies. We need libssl-dev.

So yea, one step forward, I guess.

Is it possible to specify a version in pip and using apt-get to install it at the same time?

**Comment by semenko** [comment]
""Is it possible to specify a version in pip and using apt-get to install it at the same time?""

Not entirely sure what you mean. I think you can have pip not upgrade the package if it finds it in system site packages?

**Comment by TheNavigat** [comment]
Oh, I thought you wanted to specify pip's version, not Selenium. Got what you meant right now.

So, how can you specify Selenium's version through pip?

**Comment by semenko** [comment]
(I'm just guessing that the version in pip is incompatible or broken.)

In requirements.txt, set packagename==1.2.3 (or packagename>=1.2.3)

It looks like that's just a spurious error, though: https://github.com/SeleniumHQ/selenium/issues/994

**Comment by TheNavigat** [comment]
I got stuck at a few other errors as well. As a matter of fact, I couldn't even get Iceweasel to start.

```
Using binary at '/usr/bin/firefox'.

(process:30371): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Using profile at '/tmp/tmp.mdyJ6CHJWi'.

(process:30375): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[30375] WARNING: Locale not supported by C library.
	Using the fallback 'C' locale.: 'glib warning', file /tmp/buildd/iceweasel-38.2.1esr/toolkit/xre/nsSigHandlers.cpp, line 140

(iceweasel:30375): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: no display specified
```

I'm not sure if I should skip that since the whole kit is supposedly made for the desktop version of Debian or not, but if yes, then I guess I'll need to download the whole Debian desktop ISO and run it locally.

**Comment by TheNavigat** [comment]
Okay so my Debian installation is ready. I cloned the repo, ran the tests, and I got stuck at the same error. I reverted to an old commit, https://github.com/EFForg/https-everywhere/commit/495efe7b2aefbf3e677cd63984d1e9aa8cbfec3c, I ran the tests again, and surprise, the same error appears.

So yea, we need someone who worked on FF tests.

**Comment by TheNavigat** [comment]
@jsha Can you please take a look?

**Comment by TheNavigat** [comment]
Is there someone else who can help with this, hopefully one who has enough time to look into it? :/

**Comment by semenko** [comment]
It's not critical now -- and the EFF folks are pretty busy with the "Let's Encrypt" push.

You could play with Docker a bit more -- and see if this is a Firefox issue. I see a bunch of threads on "Loop is not enabled" and "modules/loop/MozLoopService.jsm"

**Comment by TheNavigat** [comment]
Yea, that was the first thing I guessed when I saw jsha's feed :/

On the other hand, I shared somewhere Travis CI's team reply regarding how difficult it was to install Chromium. You mentioned that ```sudo: false``` is supposed to enable docker mode, apparently, it doesn't.

I say that because of two things. That's what one of Travis CI guys said.

```Our recently announced Docker infrastructure (http://docs.travis-ci.com/user/docker/) runs on Trusty. It can use "sudo", too, so you can check that out. Do note that some languages (PHP, for example), is not yet supported.```

And second, I don't think we're running on Trusty.

Maybe if we added the ```services: - docker``` part (as mentioned in the link above) we'll be blessed by the holy light of Shuttleworth's Ubuntu Trusty?

**Comment by semenko** [comment]
I don't think that's correct -- I think you might be confused about the Docker phrasing.

We don't have a Docker image that we're testing on. We are, however, running on their containerized infrastructure, which runs on Docker. See the start of every log:
https://travis-ci.org/EFForg/https-everywhere#L165
and this post:
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

I don't think it makes a ton of sense for us to make a Docker image for HTTPSe right now — it's a bunch of overhead and complexity to replace a few install lines.

Adding `services: - docker` would require us to build a docker image, add some docker pull/start/run lines, etc.

**Comment by TheNavigat** [comment]
Oh, I see. I guess you're right, then.

**Comment by drazisil** [comment]
Just to chime in on the loop.enabled bit (since your issue here helped me in tackling an issue with mine)

The main issue is that while Firefox has loop.enabled set to true be default in the config, for reasons unknown, Iceweasel defaults to false (at least on jessie)

As far as why npm test checks the status of that config key (it will even do it with the default empty test) I have no clue.

**Comment by fuglede** [comment]
Ran into a new problem in <code>install-dev-dependencies.sh</code>:

	$ sudo bash install-dev-dependencies.sh 
	+ type apt-get
	+ BROWSERS='firefox chromium-browser'
	+ CHROMEDRIVER=chromium-chromedriver
	++ lsb_release -is
	+ [[ Debian == \D\e\b\i\a\n ]]
	+ BROWSERS='iceweasel chromium'
	+ CHROMEDRIVER=chromedriver
	+ sudo apt-get install libxml2-dev libxml2-utils libxslt1-dev python-dev iceweasel chromium zip sqlite3 python-pip libcurl4-openssl-dev libssl-dev chromedriver
	Indlæser pakkelisterne... Færdig
	Opbygger afhængighedstræ        
	Læser tilstandsoplysninger... Færdig
	libcurl4-openssl-dev er allerede den nyeste version.
	libxml2-dev er allerede den nyeste version.
	libxml2-utils er allerede den nyeste version.
	libxslt1-dev er allerede den nyeste version.
	libssl-dev er allerede den nyeste version.
	python-dev er allerede den nyeste version.
	python-pip er allerede den nyeste version.
	sqlite3 er allerede den nyeste version.
	zip er allerede den nyeste version.
	chromedriver er allerede den nyeste version.
	chromium er allerede den nyeste version.
	iceweasel er allerede den nyeste version.
	Følgende pakker blev installeret automatisk, og behøves ikke længere:
	  libfglrx:i386 libjs-sphinxdoc libxinerama1:i386 python-concurrent.futures python-livestreamer python-singledispatch rtmpdump
	Brug »apt-get autoremove« til at fjerne dem.
	0 opgraderes, 0 nyinstalleres, 0 afinstalleres og 1 opgraderes ikke.
	+ git submodule init
	+ git submodule update
	+ pip install --user --no-allow-insecure --no-allow-external -r requirements.txt
	Traceback (most recent call last):
	  File "/usr/bin/pip", line 9, in <module>
	    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
	    return get_distribution(dist).load_entry_point(group, name)
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
	    return ep.load()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
	    ['__name__'])
	  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
	    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
	  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
	    from pip.download import path_to_url
	  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
	    from requests.compat import IncompleteRead
	ImportError: cannot import name IncompleteRead

**Comment by semenko** [comment]
Hm, any chance this is a local pip problem?

See: https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread/27341847#27341847

& proposed solution:
````
apt-get remove python-pip
easy_install pip
```

**Comment by fuglede** [comment]
Yeah, came across the same one. It's not super local if it affects all Debian installations though; and <code>python-pip</code> is installed as part of the same bash script. I would try the fix to see if it could be modified to cover that, but that does not appear to be working at the moment:

	$ sudo easy_install pip
	Searching for pip
	Reading https://pypi.python.org/simple/pip/
	Best match: pip 7.1.2
	Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz#md5=3823d2343d9f3aaab21cf9c917710196
	error: [Errno 104] Connection reset by peer

**Comment by TheNavigat** [comment]
So, everything works now?

**Comment by fuglede** [comment]
@TheNavigat: Nah, this was really unrelated to the old Debian related issue which persists (but which has a [nonsensical fix](#issuecomment-138254489)). I'm not entirely happy with the solution to the new issue either: having people use a bunch of different package managers for rather simple tasks seems undesirable.

**Comment by TheNavigat** [comment]
Regarding the new issue, I'm not sure how can we fix that on our own side. Not even sure whether it's a bug in some pip version, where if you install another version using easy_install it'd work.

Not sure if it's worth researching, since as I mentioned above, I'm not sure how can we fix it on our own side. Maybe require a specific version of pip? A little bit too much, right?

**Comment by fuglede** [comment]
I haven't tested their interoperation but it seems like all Python modules are in the Jessie repos, except from <code>bsdiff4</code>. A bit unfortunate. But yes, it is not the most pressing issue.

**Comment by sampablokuper** [comment]
With Debian Jessie 8.4 (x86), `install-dev-dependencies.sh` seems to work OK, but `test.sh` still fails.

    $ bash install-dev-dependencies.sh
    + type apt-get
    + BROWSERS='firefox chromium-browser'
    + CHROMEDRIVER=chromium-chromedriver
    ++ lsb_release -is
    + [[ Debian == \D\e\b\i\a\n ]]
    + BROWSERS='iceweasel chromium'
    + CHROMEDRIVER=chromedriver
    + sudo apt-get install libxml2-dev libxml2-utils libxslt1-dev python-dev iceweasel chromium zip sqlite3 python-pip libcurl4-openssl-dev xvfb libssl-dev git chromedriver
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    libcurl4-openssl-dev is already the newest version.
    git is already the newest version.
    libxml2-dev is already the newest version.
    libxml2-utils is already the newest version.
    libxslt1-dev is already the newest version.
    python-dev is already the newest version.
    python-pip is already the newest version.
    sqlite3 is already the newest version.
    xvfb is already the newest version.
    zip is already the newest version.
    chromedriver is already the newest version.
    chromium is already the newest version.
    iceweasel is already the newest version.
    libssl-dev is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    + git submodule init
    + git submodule update
    + pip install --user --no-allow-insecure --no-allow-external -r requirements.txt
    Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
    Requirement already satisfied (use --upgrade to upgrade): pycurl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): regex in /home/sampablokuper/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
    Requirement already satisfied (use --upgrade to upgrade): bsdiff4 in /home/sampablokuper/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
    Collecting python-Levenshtein (from -r requirements.txt (line 5))
      Using cached python-Levenshtein-0.12.0.tar.gz
    Collecting selenium (from -r requirements.txt (line 6))
      Using cached selenium-2.53.2-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/sampablokuper/.local/lib/python2.7/site-packages (from python-Levenshtein->-r requirements.txt (line 5))
    Building wheels for collected packages: python-Levenshtein
      Running setup.py bdist_wheel for python-Levenshtein ... done
      Stored in directory: /home/sampablokuper/.cache/pip/wheels/c0/83/e9/b2cc2876e175d04091caf4e9f5de564ff2503b1f1885e7c3ba
    Successfully built python-Levenshtein
    Installing collected packages: python-Levenshtein, selenium
    Successfully installed python-Levenshtein-0.12.0 selenium-2.53.2
    + cd test/rules
    + pip install --user -r requirements.txt
    Requirement already satisfied (use --upgrade to upgrade): pycurl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
    Requirement already satisfied (use --upgrade to upgrade): regex in /home/sampablokuper/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): bsdiff4 in /home/sampablokuper/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
    Requirement already satisfied (use --upgrade to upgrade): python-Levenshtein in /home/sampablokuper/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/sampablokuper/.local/lib/python2.7/site-packages (from python-Levenshtein->-r requirements.txt (line 4))
    + cd -
    /home/sampablokuper/Documents/projects/https-everywhere
    + cd test/chromium
    + pip install --user -r requirements.txt
    Requirement already satisfied (use --upgrade to upgrade): selenium in /home/sampablokuper/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
    + cd -
    /home/sampablokuper/Documents/projects/https-everywhere
    + ln -sf ../../test.sh .git/hooks/pre-push

The above looks OK, right? However, a test still fails:

    $ bash test.sh
    + '[' -n '' ']'
    + git rev-parse
    ++ git rev-parse --show-toplevel
    + cd /home/sampablokuper/Documents/projects/https-everywhere
    + source utils/mktemp.sh
    +++ which mktemp
    ++ MKTEMP=/bin/mktemp
    ++ mktemp
    ++ /bin/mktemp
    + TMP=/tmp/tmp.xHwS9VjADV
    + trap 'rm "$TMP"' EXIT
    + '[' -d test/rules ']'
    + '[' 0 -gt 0 ']'
    + python2.7 test/rules/src/https_everywhere_checker/check_rules.py test/rules/coverage.checker.config
    + exit 0
    + rm /tmp/tmp.xHwS9VjADV
    + '[' -n '' ']'
    + git rev-parse
    ++ git rev-parse --show-toplevel
    + cd /home/sampablokuper/Documents/projects/https-everywhere
    + source utils/mktemp.sh
    +++ which mktemp
    ++ MKTEMP=/bin/mktemp
    + TEST_ADDON_PATH=./test/firefox/
    ++ mktemp -d
    ++ /bin/mktemp -d
    + PROFILE_DIRECTORY=/tmp/tmp.EpS5qMS5b7
    + trap 'rm -r "$PROFILE_DIRECTORY"' EXIT
    + HTTPSE_INSTALL_DIRECTORY=/tmp/tmp.EpS5qMS5b7/extensions/https-everywhere-eff@eff.org
    + ./makexpi.sh
    Generating ruleset DB
    Validation of included rulesets completed.

    Validation of rulesets against relaxng.xml succeeded.
    Total included rules: 20383
    Rules disabled by default: 4341
    Created pkg/https-everywhere-5.1.9~56c9667-eff.xpi and pkg/https-everywhere-5.1.9~56c9667-amo.xpi
    ++ tail -1
    ++ ls -tr pkg/https-everywhere-5.1.9~56c9667-eff.xpi
    + XPI_NAME=pkg/https-everywhere-5.1.9~56c9667-eff.xpi
    + rsync -a test/firefox/test_profile_skeleton/ /tmp/tmp.EpS5qMS5b7
    + unzip -qd /tmp/tmp.EpS5qMS5b7/extensions/https-everywhere-eff@eff.org pkg/https-everywhere-5.1.9~56c9667-eff.xpi
    + '[' '!' -f addon-sdk/bin/activate ']'
    + '[' '!' -d /tmp/tmp.EpS5qMS5b7/extensions/https-everywhere-eff@eff.org ']'
    ++ which xvfb-run
    + '[' -z '' -a -n /usr/bin/xvfb-run ']'
    + XVFB_RUN=xvfb-run
    + pushd addon-sdk
    ~/Documents/projects/https-everywhere/addon-sdk ~/Documents/projects/https-everywhere
    + source bin/activate
    ++ deactivate nondestructive
    ++ '[' -n '' ']'
    ++ '[' -n /bin/bash -o -n '' ']'
    ++ hash -r
    ++ '[' -n '' ']'
    ++ PYTHONPATH=
    ++ export PYTHONPATH
    ++ unset _OLD_PYTHONPATH
    ++ unset CUDDLEFISH_ROOT
    ++ unset VIRTUAL_ENV
    ++ '[' '!' nondestructive = nondestructive ']'
    ++ _OLD_PYTHONPATH=
    ++ _OLD_VIRTUAL_PATH=/home/sampablokuper/.npm/bin:/home/sampablokuper/.rvm/gems/ruby-2.2.1/bin:/home/sampablokuper/.rvm/gems/ruby-2.2.1@global/bin:/home/sampablokuper/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/sampablokuper/.rvm/bin:/home/sampablokuper/.rvm/bin:/home/sampablokuper/.local/bin/
    +++ pwd
    ++ VIRTUAL_ENV=/home/sampablokuper/Documents/projects/https-everywhere/addon-sdk
    ++ '[' xlinux-gnu = xmsys ']'
    ++ CUDDLEFISH_ROOT=/home/sampablokuper/Documents/projects/https-everywhere/addon-sdk
    ++ PYTHONPATH=/home/sampablokuper/Documents/projects/https-everywhere/addon-sdk/python-lib:
    ++ PATH=/home/sampablokuper/Documents/projects/https-everywhere/addon-sdk/bin:/home/sampablokuper/.npm/bin:/home/sampablokuper/.rvm/gems/ruby-2.2.1/bin:/home/sampablokuper/.rvm/gems/ruby-2.2.1@global/bin:/home/sampablokuper/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/sampablokuper/.rvm/bin:/home/sampablokuper/.rvm/bin:/home/sampablokuper/.local/bin/
    +++ pwd
    ++ VIRTUAL_ENV=/home/sampablokuper/Documents/projects/https-everywhere/addon-sdk
    ++ export CUDDLEFISH_ROOT
    ++ export PYTHONPATH
    ++ export PATH
    ++ _OLD_VIRTUAL_PS1=
    +++ basename /home/sampablokuper/Documents/projects/https-everywhere/addon-sdk
    ++ '[' addon-sdk = __ ']'
    +++ basename /home/sampablokuper/Documents/projects/https-everywhere/addon-sdk
    ++ PS1='(addon-sdk)'
    ++ export PS1
    ++ '[' -n /bin/bash -o -n '' ']'
    ++ hash -r
    ++ python -c 'from jetpack_sdk_env import welcome; welcome()'
    Welcome to the Add-on SDK. For the docs, visit https://addons.mozilla.org/en-US/developers/docs/sdk/latest/
    + popd
    ~/Documents/projects/https-everywhere
    + type cfx
    + pushd ./test/firefox/
    ~/Documents/projects/https-everywhere/test/firefox ~/Documents/projects/https-everywhere
    + '[' '' == --justrun ']'
    + echo 'running tests'
    running tests
    + xvfb-run cfx test --profiledir=/tmp/tmp.EpS5qMS5b7 --verbose
    Using binary at '/usr/bin/firefox'.

    (process:6156): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Using profile at '/tmp/tmp.EpS5qMS5b7'.

    (process:6162): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Xlib:  extension "RANDR" missing on display ":99".
    HTTPS Everywhere DBUG: Got profile-after-change
    HTTPS Everywhere INFO: Not activating rules that trigger mixed content errors.
    HTTPS Everywhere NOTE: Loading targets took 0.444 seconds
    SSL Observatory DBUG: Loaded observatory component!
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://tiles.services.mozilla.com/v2/links/fetch/en-GB
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://tiles.services.mozilla.com/v2/links/fetch/en-GB
    HTTPS Everywhere DBUG: No applicable list rewriting https://tiles.services.mozilla.com/v2/links/fetch/en-GB
    HTTPS Everywhere DBUG: Processing https://tiles.services.mozilla.com/v2/links/fetch/en-GB
    HTTPS Everywhere DBUG: For target tiles.services.mozilla.com, found no ids in DB
    HTTPS Everywhere DBUG: For target *.services.mozilla.com, found no ids in DB
    HTTPS Everywhere DBUG: For target tiles.*.mozilla.com, found no ids in DB
    HTTPS Everywhere DBUG: For target tiles.services.*.com, found no ids in DB
    HTTPS Everywhere DBUG: For target tiles.services.mozilla.*, found no ids in DB
    HTTPS Everywhere INFO: For target *.mozilla.com, found ids 10697
    HTTPS Everywhere DBUG: Parsing Mozilla.com (partial)
    HTTPS Everywhere DBUG: Cookie rule .*\.mozilla\.com$ .+
    HTTPS Everywhere DBUG: Potentially applicable rules for tiles.services.mozilla.com:
    HTTPS Everywhere DBUG:   Mozilla.com (partial)
    HTTPS Everywhere DBUG: Adding listener for toolbarButton init.
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    HTTPS Everywhere DBUG: No applicable list rewriting https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    HTTPS Everywhere DBUG: Processing https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    HTTPS Everywhere DBUG: For target location.services.mozilla.com, found no ids in DB
    HTTPS Everywhere DBUG: For target *.services.mozilla.com, found no ids in DB
    HTTPS Everywhere DBUG: For target location.*.mozilla.com, found no ids in DB
    HTTPS Everywhere DBUG: For target location.services.*.com, found no ids in DB
    HTTPS Everywhere DBUG: For target location.services.mozilla.*, found no ids in DB
    HTTPS Everywhere INFO: For target *.mozilla.com, found ids 10697
    HTTPS Everywhere DBUG: Potentially applicable rules for location.services.mozilla.com:
    HTTPS Everywhere DBUG:   Mozilla.com (partial)
    console.error:
      [CustomizableUI]
      Custom widget with id loop-button does not return a valid node
    HTTPS Everywhere DBUG: Removing listener for toolbarButton init.
    HTTPS Everywhere NOTE: No expando for about:blank
    HTTPS Everywhere DBUG: Got http-on-modify-request: http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for http://ocsp.digicert.com/
    HTTPS Everywhere INFO: Channel with HTTPS rewrites forbidden, deeming OCSP, for http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: Got http-on-examine-response @ http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for http://ocsp.digicert.com/
    HTTPS Everywhere INFO: http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: Got http-on-examine-response @ https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    HTTPS Everywhere INFO: https://location.services.mozilla.com/v1/country?key=no-mozilla-api-key
    console.error:
      [CustomizableUI]
      Custom widget with id loop-button does not return a valid node
    SSL Observatory INFO: in getProxySettings()
    SSL Observatory INFO: CASE: try localhost:9050
    SSL Observatory INFO: Using proxy: [object Object]
    SSL Observatory INFO: Got observatory url + nonce: https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    SSL Observatory INFO: in getProxySettings()
    SSL Observatory INFO: CASE: try localhost:9050
    SSL Observatory INFO: Using proxy: [object Object]
    SSL Observatory INFO: Specifying proxy: [xpconnect wrapped nsIProxyInfo]
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    HTTPS Everywhere DBUG: No applicable list rewriting https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    HTTPS Everywhere DBUG: Processing https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    HTTPS Everywhere DBUG: For target check.torproject.org, found no ids in DB
    HTTPS Everywhere INFO: For target *.torproject.org, found ids 16637
    HTTPS Everywhere DBUG: Parsing Tor Project
    HTTPS Everywhere DBUG: Cookie rule ^(?:.*\.)?torproject\.org$ .+
    HTTPS Everywhere DBUG: For target check.*.org, found no ids in DB
    HTTPS Everywhere DBUG: For target check.torproject.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for check.torproject.org:
    HTTPS Everywhere DBUG:   Tor Project
    HTTPS Everywhere DBUG: Got sessionstore-windows-restored
    Running tests on Iceweasel 38.8.0/Gecko 38.8.0 ({ec8030f7-c20a-464f-9b0e-13a3a9e97384}) under linux/x86.
    console.info: https-everywhere-tests: executing 'https-everywhere-tests/tests/test-httpse-installed.test httpse installed'
    console.info: https-everywhere-tests: pass: Test that HTTPSEverywhere is defined
    console.info: https-everywhere-tests: pass: Test that HTTPSEverywhere.observe is a function
    console.error: https-everywhere-tests:
      fail:
      There was an uncaught Promise rejection: Error: loop is not enabled @ resource:///modules/loop/MozLoopService.jsm:1110
    this.MozLoopService.initialize<@resource:///modules/loop/MozLoopService.jsm:1110:29
    TaskImpl_run@resource://gre/modules/Task.jsm:314:40
    TaskImpl@resource://gre/modules/Task.jsm:275:3
    createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:249:14
    LoopUI.init@chrome://browser/content/browser.js:4485:7
    gBrowserInit._delayedStartup@chrome://browser/content/browser.js:11917:5

    console.trace: https-everywhere-tests:
    _ecated/unit-test.js 108 fail
    _ecated/unit-test.js 71 TestRunner.prototype._uncaughtErrorObserver
    _/Promise-backend.js 200 PendingErrors.report
    _/Promise-backend.js 212 PendingErrors.flush
    _/Promise-backend.js 614 Promise.Debugging.flushUncaughtErrors
    _ecated/unit-test.js 322 done
    _ecated/unit-test.js 564 start
    _ecated/unit-test.js 522 startMany/runNextTest/<
    _/Promise-backend.js 867 Handler.prototype.process
    _/Promise-backend.js 746 this.PromiseWalker.walkerLoop
    _/Promise-backend.js 688 this.PromiseWalker.scheduleWalkerLoop/<
                         0

    HTTPS Everywhere DBUG: Got http-on-modify-request: http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for http://ocsp.digicert.com/
    HTTPS Everywhere INFO: Channel with HTTPS rewrites forbidden, deeming OCSP, for http://ocsp.digicert.com/
    console.info: https-everywhere-tests: executing 'https-everywhere-tests/tests/test-httpse-installed.test httpse potentiallyApplicableRulesets'
    HTTPS Everywhere DBUG: For target www.eff.org, found no ids in DB
    HTTPS Everywhere INFO: For target *.eff.org, found ids 4927
    HTTPS Everywhere DBUG: Parsing EFF
    HTTPS Everywhere DBUG: Cookie rule ^.*\.eff\.org$ .*
    HTTPS Everywhere DBUG: For target www.*.org, found no ids in DB
    HTTPS Everywhere DBUG: For target www.eff.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for www.eff.org:
    HTTPS Everywhere DBUG:   EFF
    console.info: https-everywhere-tests: pass: Test that HTTPSE finds one applicable rule for www.eff.org
    console.info: https-everywhere-tests: executing 'https-everywhere-tests/tests/test-httpse-installed.test sample ruleset'
    HTTPS Everywhere DBUG: Got http-on-modify-request: http://libssh.org/robots.txt
    HTTPS Everywhere NOTE: No expando for about:blank
    HTTPS Everywhere DBUG: Alist serial #1 for about:blank
    HTTPS Everywhere DBUG: Processing http://libssh.org/robots.txt
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: Parsing libssh.org (partial)
    HTTPS Everywhere DBUG: Cookie rule ^www\.libssh\.org$ .+
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    HTTPS Everywhere DBUG: Rewrote http://libssh.org/robots.txt -> https://libssh.org/robots.txt using Libssh.org.xml: /^http:/ -> https:
    HTTPS Everywhere INFO: active rule libssh.org (partial) in about:blank -> about:blank serial 1
    HTTPS Everywhere DBUG: http://libssh.org/robots.txt: Redirection limit is 20
    HTTPS Everywhere INFO: Using nsIHttpChannel.redirectTo: http://libssh.org/robots.txt -> https://libssh.org/robots.txt
    HTTPS Everywhere INFO: Setting icon counter to: 1
    HTTPS Everywhere DBUG: Got http-on-examine-response @ http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for http://ocsp.digicert.com/
    HTTPS Everywhere INFO: http://ocsp.digicert.com/
    HTTPS Everywhere DBUG: Got onChannelRedirect to https://libssh.org/robots.txt
    HTTPS Everywhere DBUG: Processing https://libssh.org/robots.txt
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://libssh.org/robots.txt
    HTTPS Everywhere DBUG: Processing https://libssh.org/robots.txt
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    HTTPS Everywhere DBUG: Got http-on-examine-response @ https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    HTTPS Everywhere INFO: https://check.torproject.org/?TorButton=true#0.70529625739098980.37447020389178576
    SSL Observatory INFO: Tor check succeeded.
    HTTPS Everywhere DBUG: Got http-on-modify-request: http://ocsp.startssl.com/
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for http://ocsp.startssl.com/
    HTTPS Everywhere INFO: Channel with HTTPS rewrites forbidden, deeming OCSP, for http://ocsp.startssl.com/
    console.log: https-everywhere-tests: [JavaScript Error: "Unix error 2 during operation open on file /tmp/tmp.EpS5qMS5b7/directoryLinks.json (No such file or directory)" {file: "resource:///modules/DirectoryLinksProvider.jsm" line: 291}]
    HTTPS Everywhere DBUG: Got http-on-examine-response @ http://ocsp.startssl.com/
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for http://ocsp.startssl.com/
    HTTPS Everywhere INFO: http://ocsp.startssl.com/
    SSL Observatory INFO: SHA-256 hash of cert chain for libssh.org is 1E683B65B27BEF54F825A408998098E28E7A2AB00DA50CDD9A3E5450C828DB67
    SSL Observatory INFO: Cert chain is NOT whitelisted. Proceeding with submission.
    SSL Observatory INFO: Got root cert at position: 2
    SSL Observatory INFO: Got a private root cert. Ignoring domain libssh.org with root C93B0D8441FCA47679230857DE101916A3F1333FE242BFCFC5D14E8F394298406810D1A0
    HTTPS Everywhere DBUG: Got http-on-examine-response @ https://libssh.org/robots.txt
    HTTPS Everywhere DBUG: Got on location change!
    HTTPS Everywhere DBUG: Alist serial #2 for https://libssh.org/robots.txt
    HTTPS Everywhere DBUG: Got on state change
    HTTPS Everywhere DBUG: Processing https://libssh.org/robots.txt
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    HTTPS Everywhere DBUG: Would libssh.org (partial) match https://libssh.org/robots.txt?  serial 2
    HTTPS Everywhere INFO: moot rule libssh.org (partial) in https://libssh.org/robots.txt serial 2
    HTTPS Everywhere DBUG: populating using alist #2
    HTTPS Everywhere INFO: Setting icon counter to: 1
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere NOTE: getBrowserForChannel: aTab was null for https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere DBUG: No applicable list rewriting https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere DBUG: Processing https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    console.info: https-everywhere-tests: pass: Test that LibSSH URLs are rewritten to HTTPS.
    HTTPS Everywhere NOTE: No expando for about:blank
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere NOTE: getBrowserForChannel: aTab was null for https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere DBUG: No applicable list rewriting https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere DBUG: Processing https://libssh.org/favicon.ico#-moz-resolution=16,16
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    HTTPS Everywhere DBUG: Got http-on-modify-request: https://libssh.org/favicon.ico
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://libssh.org/favicon.ico
    HTTPS Everywhere DBUG: No applicable list rewriting https://libssh.org/favicon.ico
    HTTPS Everywhere DBUG: Processing https://libssh.org/favicon.ico
    HTTPS Everywhere INFO: For target libssh.org, found ids 9356
    HTTPS Everywhere DBUG: For target *.org, found no ids in DB
    HTTPS Everywhere DBUG: For target libssh.*, found no ids in DB
    HTTPS Everywhere DBUG: Potentially applicable rules for libssh.org:
    HTTPS Everywhere DBUG:   libssh.org (partial)
    console.info: https-everywhere-tests: executing 'https-everywhere-tests/tests/test-main.test main'
    console.info: https-everywhere-tests: pass: Unit test running!
    SSL Observatory INFO: SHA-256 hash of cert chain for libssh.org is 1E683B65B27BEF54F825A408998098E28E7A2AB00DA50CDD9A3E5450C828DB67
    SSL Observatory INFO: Cert chain is NOT whitelisted. Proceeding with submission.
    SSL Observatory INFO: Got root cert at position: 2
    SSL Observatory INFO: Got a private root cert. Ignoring domain libssh.org with root C93B0D8441FCA47679230857DE101916A3F1333FE242BFCFC5D14E8F394298406810D1A0
    HTTPS Everywhere DBUG: Got http-on-examine-response @ https://libssh.org/favicon.ico
    HTTPS Everywhere DBUG: getBrowserForChannel: no loadContext for https://libssh.org/favicon.ico
    HTTPS Everywhere INFO: https://libssh.org/favicon.ico
    console.info: https-everywhere-tests: executing 'https-everywhere-tests/tests/test-main.test main async'
    console.info: https-everywhere-tests: pass: async Unit test running!

    6 of 7 tests passed.

    The following tests failed:
      https-everywhere-tests/tests/test-httpse-installed.test httpse installed: failure

    Total time: 12.545864 seconds
    Program terminated unsuccessfully.
    + rm -r /tmp/tmp.EpS5qMS5b7
    + '[' -n '' ']'
    + git rev-parse
    ++ git rev-parse --show-toplevel
    + cd /home/sampablokuper/Documents/projects/https-everywhere
    ++ which xvfb-run
    + '[' -z '' -a -n /usr/bin/xvfb-run ']'
    + XVFB_RUN=xvfb-run
    + '[' '' == --justrun ']'
    + ./makecrx.sh
    Building chrome version 2016.5.10
    Creating ruleset library...
    Removing whitespaces and comments...
    chrome/content/rules/default.rulesets passed XML validity test.
    Unsigned package has shasum: 718695795170f337dde77c927647b2adeb0de4d6  /home/sampablokuper/Documents/projects/https-everywhere/pkg/crx.zip
    Total included rules: 20383
    Rules disabled by default: 4341
    Created pkg/https-everywhere-2016.5.10~pre.crx
    + echo 'running tests'
    running tests
    ++ ls -tr pkg/https-everywhere-2016.5.10~pre.crx
    ++ tail -1
    + CRX_NAME=pkg/https-everywhere-2016.5.10~pre.crx
    + xvfb-run python2.7 test/chromium/script.py pkg/https-everywhere-2016.5.10~pre.crx

    Chromium: HTTP to HTTPS redirection successful

**Comment by Hainish** [comment]
This appears to be fixed in the latest, closing
