### ISSUE TITLE
The green checkmark (showing the rule is enabled) is not visible

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#4082]
There are two modes, apparently: 
1. Either the rule is enabled but no green checkmark can be seen, although the rule name is green(or sometimes gray depending on if it was re-enabled on a different webpage and you're looking at the webpage which was loaded with it disabled - but still no red checkmark on this webpage)
2. Or the rule is disabled and the red X mark appears, with rule name being gray.

Tested https-everywhere commit: 9c0aad1329a3a04d24d555b7c69e18d40333141f HTTPS-Everywhere 5.1.2  Last Updated: 02/03/2016

Expected: the enabled rules to have the green checkmark, but they are lacking it(for unknown reasons) as seen here:

![lack of green checkmark](https://cloud.githubusercontent.com/assets/17016209/12795886/82e16310-cabc-11e5-9116-8bb729719635.png)

Clicking one of them, makes it red:
![red x](https://cloud.githubusercontent.com/assets/17016209/12795887/82e6b248-cabc-11e5-92f8-81c5f1833b44.png)

Tested on firefox 44.0, here's `about:buildconfig`
```
Build platform
target
x86_64-pc-linux-gnu
Build tools
Compiler 	Version 	Compiler flags
x86_64-pc-linux-gnu-gcc 	5.3.0 	-Wall -Wempty-body -Wpointer-to-int-cast -Wsign-compare -Wtype-limits -Wno-unused -Wcast-align -pipe -march=native -g0 -fno-stack-protector -fPIC -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe
x86_64-pc-linux-gnu-g++ 	5.3.0 	-Wall -Wempty-body -Woverloaded-virtual -Wsign-compare -Wwrite-strings -Wno-invalid-offsetof -Wcast-align -pipe -march=native -g0 -fno-stack-protector -fPIC -fno-exceptions -fno-strict-aliasing -fno-rtti -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -freorder-blocks -Os -fomit-frame-pointer
Configure arguments

--enable-application=browser --enable-optimize --disable-pedantic --disable-updater --disable-strip --disable-install-strip --disable-installer --disable-strip-libs --disable-profilelocking --enable-single-profile --disable-profilesharing --with-system-zlib --enable-pango --enable-svg --with-system-bz2 --disable-official-branding --with-branding=browser/branding/aurora --disable-debug --disable-tests --disable-debug-symbols --enable-startup-notification --disable-necko-wifi --enable-dbus --enable-ogg --enable-wave --disable-ion --with-system-nspr --with-nspr-prefix=/usr --with-system-nss --with-nss-prefix=/usr --x-includes=/usr/include --x-libraries=/usr/lib64 --prefix=/usr --libdir=/usr/lib64 --enable-system-hunspell --disable-gnomeui --enable-gio --disable-crashreporter --with-system-png --enable-system-ffi --disable-gold --disable-skia --disable-gconf --with-intl-api --enable-default-toolkit=cairo-gtk3 --enable-jemalloc --enable-replace-malloc --target=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --disable-ffmpeg --disable-gstreamer --enable-pulseaudio --disable-system-cairo --enable-system-sqlite --with-system-jpeg --with-system-icu --without-system-libvpx --with-google-api-keyfile=/var/tmp/portage/www-client/firefox-44.0/work/firefox-44.0/google-api-key --disable-mailnews --with-default-mozilla-five-home=/usr/lib64/firefox --enable-extensions=default
```

**Comment by vgturtle127** [comment]
@aoaaxy Have you tried 5.1.3?

**Comment by aoaaxy** [comment]
I just tested latest commit 9f7529d2313725cb3395ac8e8de8436025402590  (it says it's 5.1.3 too)
The issue is still present though.

Firefox 44.0.2

**Comment by vgturtle127** [comment]
@aoaaxy Yeah, I can reproduce this. I forgot I was in Chrome. :blush: 

I tested on 64-bit Firefox 44.0.2, 64-bit Firefox Developer Edition, all on 64-bit Windows 10 Pro.

I used HTTPS Everywhere 5.1.3 from AMO.

@fuglede @jsha

**Comment by aoaaxy** [comment]
Nice @vgturtle127 . Thanks for confirming, appreciate it!

**Comment by vgturtle127** [comment]
@aoaaxy Sure, no problem.

**Comment by fuglede** [comment]
In my testing, the ordinary 'ruleset active' icons work just fine on current master, but indeed, those that are associated to 'moot' rulesets vanished a while ago:

![moot1](https://cloud.githubusercontent.com/assets/6169306/13725932/8916eae2-e8a9-11e5-9a6d-5036f7985512.png)

#4349 reintroduces those:

![moot2](https://cloud.githubusercontent.com/assets/6169306/13725935/92f42ac0-e8a9-11e5-9e03-250553e5e29c.png)

**Comment by jsha** [comment]
Fixed by #4349.

**Comment by vgturtle127** [comment]
@jsha Thanks!

**Comment by fuglede** [comment]
Looks like this one is still an issue (and in fact the PR was never actually merged); reopening.
