### ISSUE TITLE
HTTPS Everywhere Chrome 2016.10.20 corrupted even on Chrome 54+

### ISSUE THREAD

**Issue by jgillula** [EFForg/https-everywhere#7456]
We've had at least two reports of the "This extension may have been corrupted" issue on HTTPS Everywhere 2016.10.20, one on Chrome 54.0.2840.71 m (64-bit), and the other on 54.0.2840.59 (64-bit).

**Comment by farmertammy** [comment]
not working here either with the same error. Win10, Chrome 54.0.2840.71 m (64-bit), HTTPS Everywhere 2016.10.20. Have tried removing and adding from store and eff site as well as multiple repair attempts on each.

**Comment by gloomy-ghost** [comment]
It would be great if you could provide some details, or report to [here](https://bugs.chromium.org/p/chromium/issues/detail?id=643814#c37) straightly since it's not https everywhere's fault.

**Comment by Pysis868** [comment]
I have HTTPS Everywhere currently working on my Mac 10.11.5 with Chrome 54, but it's not working, even with a Chrome Repair and manual extension re-install, on Windows 10 Pro (that's probably behind some security updates) and Chrome 53.

**Comment by gloomy-ghost** [comment]
@Pysis868 Please try to upgrade to Chrome 54 first

**Comment by yochananmarqos** [comment]
The extension works fine on Chrome 54 stable, but it shows corrupted on 55 beta.

HTTPS Everywhere 2016.11.8
Chrome 55.0.2883.44 beta (64-bit)
Linux Mint 18 Sarah Cinnamon Edition

**Comment by hao19** [comment]
Getting the extension corrupted error on chrome 54 (64-bit), windows 7 SP1 clean install

**Comment by Pysis868** [comment]
My Chrome on Windows 10 crashed (after who knows how long :) ).  Once restarted, is at version 54.0.2840.99 m.

Repaired the HTTPS Everywhere Extension, this time the process looks like it did more by removing, re-downloading, and installing it.  Now it appears to work!

**Comment by kontinuity** [comment]
The extension is has this issue with Mac 10.12.1 and Chrome Version 54.0.2840.98 (64-bit)

**Comment by stealthsubgm** [comment]
HTTPS Everywhere 2016.11.8 corrupted on Chrome 54.0.2840.99 m (64-bit).  Repair does not work ; uninstall and then reinstall adds HTTPS E again, but immediately shows it as corrupted -- again - repair does not work on the reinstalled extension.  See attached file.  
One thing to note:  ALL of my other extensions have the option "Allow in incognito" -- HTTPS E does not -- but it was working not too long ago.

![https everywhere corrupted_111716](https://cloud.githubusercontent.com/assets/23530383/20402221/ceab8ae2-acc9-11e6-86b5-97187c04ee80.jpg)

**Comment by tthrift** [comment]
HTTPS Everywhere 2016.11.8 corrupted on Chrome 54.0.2840.98 under OS X 10.11.6
"Repair" fails to repair
delete extension, restart Chrome, install extension --> seems to install then status reverts to corrupted.

**Comment by zardozman** [comment]
2016.11.30 corrupted on Chrome 53.0.2785.143, "Repair" failed.

It is of note that this happens whenever the extension updates AFTER I have changed, disabled or added a rule, and the Chrome version does NOT store custom rules or rule changes in the expected files as the Firefox version does. If I change no settings, the extension does not become corrupt.

I believe the Chrome version is improperly storing rule changes, leading to corruption being detected when the extension updates and Chrome re-verifies it.

**Comment by gloomy-ghost** [comment]
@zardozman The custom rules of HTTPS-EW for Chrome are stored in LocalStorage because Chrome doesn't allow changes in files.

Also could you check `C:\Users\{Username}\AppData\Local\Google\Chrome\User Data\Default\Extensions\gcbommkclmclpchllfjekcdonpmejbdp\2016.11.8_0\_metadata`?

**Comment by gloomy-ghost** [comment]
@Hainish HTTPS Everywhere got corrupted on my Chrome (54, on Win10) after 11.30 release, and `_metadata` doesn't exist... Repairing helps.

**Comment by hao19** [comment]
This issue seems to be fixed in the latest Chrome 55 release.

**Comment by stealthsubgm** [comment]
Yes -- I agree -- I am not seeing the "corrupted" message anymore.
Thanks much.

On Thu, Dec 1, 2016 at 10:45 PM, hao19 [Masked] <

**Comment by wickles** [comment]
Still corrupted for me in Chrome 55 stable. Repair does not help. Removing sync data / localstorage does not help.

**Comment by yochananmarqos** [comment]
I can confirm it's working again with the latest Chrome 55 beta on Peppermint 7 (Ubuntu 16.04 base).

**Comment by wickles** [comment]
Okay, it's working for me now after trying to repair again.

**Comment by guitman444** [comment]
Not working in 55.0.2883.75 m (64-bit). Uninstalled, repaired, does not want to install without reporting being corrupted. First noticed in version 53.x upgraded to 55 and still does not want to work.

**Comment by wickles** [comment]
@guitman444 keep trying, I had the same issue but it started working eventually.

**Comment by guitman444** [comment]
Tried about 20 times thus far, giving up unless other ideas come up.

**Comment by gloomy-ghost** [comment]
@guitman444 Can you try to put [these two files](https://gist.github.com/gloomy-ghost/7466ee3e9689551b5ae00e8ade150790) into `C:\Users\{UserName}\AppData\Local\Google\Chrome\User Data\Default\Extensions\gcbommkclmclpchllfjekcdonpmejbdp\2016.11.30_0\_metadata`?

**Comment by guitman444** [comment]
Thanks! Now I was able to go to the chrome store, click the enable warning, and the icon came up and stayed up. Looks like the extension is working now.

**Comment by morbidxbean** [comment]
I too am having this issue on latest chrome.  I have read through this thread and tried everything posted.  I tried the recent post that @gloomy-ghost posted adding in them 2 lines.  I did not see a _metadata, so I created it.
No luck Any Ideas

**Comment by tthrift** [comment]
HTTPS Everywhere 2016.12.19,   Chrome 55.0.2883.95 (64-bit),   OS X 10.11.6
shows as corrupted upon install and fails to repair "Repair"

**Comment by faried** [comment]
It works for me on Chrome dev 57.0.2979.0 on Mac OS 10.12.2.  However, chrome://extensions shows an error next to it, and clicking on that says

* Unrecognized manifest key 'applications'.

This bit of the manifest file is highlighted:

```
"applications": {
      "gecko": {
         "id": "https-everywhere-eff@eff.org"
      }
   },
```

**Comment by gloomy-ghost** [comment]
@Hainish #7650 might be interesting

**Comment by diego898** [comment]
I am also still having this issue on chrome 56+

**Comment by Hainish** [comment]
Version 2017.2.13 was released yesterday, but has yet to be reviewed/deployed by the Chrome Web Store.  Once users are able to upgrade, I'm curious to see if #7650 solves the issue.

**Comment by ekumlin** [comment]
Still seeing this issue on 2017.2.13.

![The extension may have been corrupted.](https://cloud.githubusercontent.com/assets/1350074/22990847/4fd50d78-f36f-11e6-8058-7610c6946952.png)

**Comment by Hainish** [comment]
@ekumlin please comment [here](https://bugs.chromium.org/p/chromium/issues/detail?id=643814) with as much info as possible regarding your configuration and versioning.

**Comment by ekumlin** [comment]
@Hainish Thanks for the pointer. I will post there if I can repro again. I had a consistent, 100% repro until I tried with `net-internals` running... and now it works fine.

**Comment by Hainish** [comment]
A comment has been made in the Chromium bugtracker.  A lot of the corruption errors are showing up due to server-side throttling on their end.  This problem should be fixed (or at least alleviated) later this week.

**Comment by o0chris0o** [comment]
FYI: I decided to change my default browser from Firefox to Chrome, then I installed HTTPS Everywhere on Chrome, everything was working fine, then I did a new Profile, to start fresh. I needed to re-installed HTTPS... in the new profile. Now on the new profile I have the problem that the extension is maybe corrupted and I cannot make it work at all, while it's still working fine on the other. I'm running Chrome 56.0.2924.87.

**Comment by jeremyn** [comment]
To paraphrase [the problem described in the Chromium bugtracker](https://bugs.chromium.org/p/chromium/issues/detail?id=643814) that @Hainish linked earlier: EFF extensions like HTTPS Everywhere and Privacy Badger are sort of unique because they don't entirely trust Google's signing process, so there are extra steps involved when a user installs or updates the extension. One of these extra steps is that the user's browser requests extra verification information from Google. The bugtracker issue is that Google doesn't always handle these requests properly, and when they don't, the user gets the corrupted extension error. That's why it sometimes happens and sometimes doesn't. Google's intended fix is to handle these extra verification requests better on their end, hopefully by later this week.

@Hainish, please correct me if this is too inaccurate.

**Comment by o0chris0o** [comment]
That make sense, now, for no apparent reason, the extension is working well.

**Comment by chanan** [comment]
I would suggest updating the FAQ section of the website and/or putting a note on the home page till this is resolved by Google.

**Comment by Hainish** [comment]
Haven't been getting reports to this effect lately.  Closing this until I get further reports.

**Comment by asmosn** [comment]
the same problem still exist  on   59.0.3071.115[stable]  and 61.0.3153.0 [dev].
and it is getting more serious ！

**Comment by Hainish** [comment]
@asmosn please open a new issue.  Screenshots are appreciated as well as any additional info you can provide (platform, is it a new profile, your extension version, etc).

**Comment by leonhu0710** [comment]
the same problem still exist on  63.0.3239.84[stable] [64 bit].Occured about 20 times thus far.

**Comment by jeremyn** [comment]
@leonhu0710 Please open a new issue with the information requested by @Hainish in his previous comment.

**Comment by leonhu0710** [comment]
@jgillula okey.
